In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
pokemon = pd.read_csv('Data/pokemon_data.csv')
pokemon

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
type_1_list=pokemon['Type 1']
type_2_list=pokemon['Type 2']

type_1_list=pd.get_dummies(
    type_1_list,
    prefix=None,
    prefix_sep='_', 
    dummy_na=True, 
    columns=['Type 1'], 
    sparse=False, 
    drop_first=False, 
    dtype=None
)

type_2_list=pd.get_dummies(
    type_2_list,
    prefix=None,
    prefix_sep='_', 
    dummy_na=True, 
    columns=['Type 2'], 
    sparse=False, 
    drop_first=False, 
    dtype=None
)


both_type= type_1_list+type_2_list
both_type

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,NaN
0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
796,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
797,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
798,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
799,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0

In [4]:
new_pokemon=pokemon.join(both_type)
new_pokemon.pop('Type 1')
new_pokemon.pop('Type 2')
new_pokemon.pop('Generation')
new_pokemon.pop('Legendary')
new_pokemon.pop('Name')
new_pokemon

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Bug,Dark,Dragon,...,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,NaN
0,1,45,49,49,65,65,45,0,0,0,...,1,0,0,0,1,0,0,0,0,0
1,2,60,62,63,80,80,60,0,0,0,...,1,0,0,0,1,0,0,0,0,0
2,3,80,82,83,100,100,80,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,4,80,100,123,122,120,80,0,0,0,...,1,0,0,0,1,0,0,0,0,0
4,5,39,52,43,60,50,65,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,50,100,150,100,150,50,0,0,0,...,0,0,0,0,0,0,1,0,0,0
796,797,50,160,110,160,110,110,0,0,0,...,0,0,0,0,0,0,1,0,0,0
797,798,80,110,60,150,130,70,0,0,0,...,0,0,0,0,0,1,0,0,0,0
798,799,80,160,60,170,130,80,0,1,0,...,0,0,0,0,0,1,0,0,0,0
799,800,80,110,120,130,90,70,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [5]:
new_pokemon.to_csv('Data/PreProcessed.csv')